EcommerceProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('search/', views.search, name='search'),
    path('accounts/', include('accounts.urls')),
    path('store/', include('store.urls')),
    path('cart/', include('carts.urls')),
    path('order/', include('order.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/urls.py
from django.urls import path
from .views import add_card, diminue_item, delete_card, delete_variant_card, add_variant_card, diminue_variant_item, checkout, index

app_name = 'cart'
urlpatterns = [
    path('', index, name='carts'),
    path('add-cart/<int:product_id>', add_card, name='add_cart'),
    path('diminue-item/<int:product_id>', diminue_item, name='diminue_item'),
    path('delete-item/<int:product_id>', delete_card, name='delete_card'),
    path('delete-item/<int:product_id>/<str:key>', delete_variant_card, name='delete_variant_card'),
    path('add-variant-cart/<int:product_id>/<str:key>', add_variant_card, name='add_variant_card'),
    path('diminue-variant-item/<int:product_id>/<str:key>', diminue_variant_item, name='diminue_variant_item'),
    path('checkout', checkout, name='checkout'),

]

templates/includes/footer.html
<footer class="section-footer border-top">
	<div class="container">
		<section class="footer-bottom border-top row">
			<div class="col-md-2">
				<p class="text-muted"> &copy {{year}} Company name </p>
			</div>
			<div class="col-md-8 text-md-center">
				<span  class="px-2">info@pixsellz.io</span>
				<span  class="px-2">+879-332-9375</span>
				<span  class="px-2">Street name 123, Avanue abc</span>
			</div>
			<div class="col-md-2 text-md-right text-muted">
				<i class="fab fa-lg fa-cc-visa"></i>
				<i class="fab fa-lg fa-cc-paypal"></i>
				<i class="fab fa-lg fa-cc-mastercard"></i>
			</div>
		</section>
	</div><!-- //container -->
</footer>

templates/includes/navbar.html
{% load static %}

<header class="section-header">
<nav class="navbar p-md-0 navbar-expand-sm navbar-light border-bottom">
<div class="container">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTop4" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTop4">
    <ul class="navbar-nav mr-auto">
    	<li class="nav-item dropdown">
		 	<a href="#" class="nav-link">   English </a>

		</li>
		<li class="nav-item dropdown">
			<a href="#" class="nav-link"> USD </a>
		</li>
    </ul>
    <ul class="navbar-nav">
		<li><a href="#" class="nav-link"> <i class="fa fa-envelope"></i> Email </a></li>
		<li><a href="#" class="nav-link"> <i class="fa fa-phone"></i> Call us </a></li>
	</ul> <!-- list-inline //  -->
  </div> <!-- navbar-collapse .// -->
</div> <!-- container //  -->
</nav>

<section class="header-main border-bottom">
	<div class="container-fluid py-2">
<div class="row align-items-center">
	<div class="col-lg-2 col-md-3 col-6">
		<a href="{% url 'home' %}" class="brand-wrap">
			<img class="logo" src="{% static 'images/logo.png' %}" alt="">
		</a> <!-- brand-wrap.// -->
	</div>
	<div class="col-lg col-sm col-md col-6 flex-grow-0">
        <div class="dropdown">
          <button class="btn btn-primary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="fa fa-bars"></i> All category
          </button>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'store' %}">All Products</a></li>
                {% for category in links %}
                    <li><a class="dropdown-item" href="{{ category.get_url }}">{{ category.category_name }}</a></li>
              {% endfor %}
          </ul>
        </div><!-- category-wrap.// -->
	</div> <!-- col.// -->
    <div class="col-1">
        <a href="{% url 'store' %}" class="btn btn-outline-primary">Store</a>
    </div>
	<div class="col-lg  col-md-6 col-sm-12 col">
		<form action="{% url 'search' %}" class="search">
			<div class="input-group w-100">
			    <input type="text" class="form-control" style="width:60%;" placeholder="Search" name="q">

			    <div class="input-group-append">
			      <button class="btn btn-primary" type="submit">
			        <i class="fa fa-search"></i>
			      </button>
			    </div>
		    </div>
		</form> <!-- search-wrap .end// -->
	</div> <!-- col.// -->
	<div class="col-lg-3 col-sm-6 col-8 order-2 order-lg-3 me-5 ">
				<div class="d-flex justify-content-end gap-5 mb-3 mb-lg-0">
					<div class="widget-header">
                        {% if user.is_authenticated %}
                            <small class="title text-muted">Welcome {{ user.username }}</small>
                        {% endif %}
						<div>
                            {% if not user.is_authenticated %}
                                <a href="{% url 'login' %}">Sign in</a> <span class="dark-transp"> | </span>
                                <a href="{% url 'register' %}"> Register</a>
                            {% else %}
                                <form action="{% url 'logout' %}" method="post">
                                    {% csrf_token %}
                                    <button type="submit" class="btn "> Log Out</button>
                                </form>
                            {% endif %}
						</div>
					</div>
					<a href="{% url 'cart:carts' %}" class="widget-header pl-3 ml-3">
						<div class="icon icon-sm rounded-circle border"><i class="fa fa-shopping-cart"></i></div>
						<span class="badge badge-pill badge-danger notify">{{count_item}}</span>
					</a>
				</div> <!-- widgets-wrap.// -->
			</div> <!-- col.// -->
</div> <!-- row.// -->
	</div> <!-- container.// -->
</section> <!-- header-main .// -->




</header> <!-- section-header.// -->