EcommerceProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('search/', views.search, name='search'),
    path('accounts/', include('accounts.urls')),
    path('store/', include('store.urls')),
    path('cart/', include('carts.urls')),
    path('order/', include('order.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/urls.py
from django.urls import path
from .views import add_card, diminue_item, delete_card, delete_variant_card, add_variant_card, diminue_variant_item, checkout, index

app_name = 'cart'
urlpatterns = [
    path('', index, name='carts'),
    path('add-cart/<int:product_id>', add_card, name='add_cart'),
    path('diminue-item/<int:product_id>', diminue_item, name='diminue_item'),
    path('delete-item/<int:product_id>', delete_card, name='delete_card'),
    path('delete-item/<int:product_id>/<str:key>', delete_variant_card, name='delete_variant_card'),
    path('add-variant-cart/<int:product_id>/<str:key>', add_variant_card, name='add_variant_card'),
    path('diminue-variant-item/<int:product_id>/<str:key>', diminue_variant_item, name='diminue_variant_item'),
    path('checkout', checkout, name='checkout'),

]

store/urls.py
from django.urls import path
from .views import index,product_detail,add_card,diminue_item

urlpatterns = [
    path('', index, name='store'),
    path('<slug:category_slug>/', index, name='product_by_category'),
    path('<slug:category_slug>/<slug:product_slug>/', product_detail, name='product_detail'),
    path('add-cart/<int:product_id>', add_card, name='add_cart'),
    path('diminue-item/<int:product_id>', diminue_item, name='diminue_item'),
]

carts/models.py
from django.db import models
from accounts.models import Account
from store.models import Product, AttributeVariant


# Create your models here.
class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.cart_id


class CartItem(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE, null=True)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)
    variant_key = models.CharField(max_length=10, blank=True, unique=False, default=None, null=True)
    variants_attribut = models.ManyToManyField(AttributeVariant)
    is_active = models.BooleanField(default=True)

    @property
    def total(self):
        return self.quantity * self.product.price

    def __str__(self):
        return str(self.product.product_name)


class CartVariant(models.Model):
    cartitem = models.ForeignKey(CartItem, on_delete=models.CASCADE, related_name='variant')
    variant_key = models.CharField(max_length=250, blank=False, unique=True)

store/models.py
from django.db import models
from django.urls import reverse

from category.models import Category
from django.utils.text import slugify


# Create your models here.
class Variant(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    product_name = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField()
    image = models.ImageField(upload_to='photos/products')
    stock = models.PositiveIntegerField(default=0)
    is_available = models.BooleanField(default=True)
    allow_variants = models.BooleanField(default=False)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)  # Save the instance first so it gets an ID
        if not self.slug:
            self.slug = slugify(f'{self.product_name}-{self.id}')
            super().save(*args, **kwargs)  # Save again to store the generated slug
        if self.stock == 0:
            self.is_available = False
            super().save(*args, **kwargs)

    def get_url(self):
        return reverse('product_detail', args=[self.category.slug, self.slug])

    def __str__(self):
        return self.product_name


class AttributeVariant(models.Model):
    attribut_variant_name = models.CharField(max_length=100, unique=True)
    is_available = models.BooleanField(default=True)
    variant = models.ForeignKey(Variant, on_delete=models.CASCADE, related_name='variant_attributes')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='variant_products')
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.product.product_name}-{self.variant.name}-{self.attribut_variant_name}"

# class ProductVariant(models.Model):
#     product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='variant_products')
#     variant = models.ManyToManyField(Variant)

carts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404

from order.forms import OrderForm
from store.models import Product
from .models import CartItem, Cart


# Create your views here.
def _card_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def add_card(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    cart_id = _card_id(request)

    attribut_variation = [value for key, value in request.POST.items() if key != "csrfmiddlewaretoken"]
    attribut_variation.sort()  # Ensure consistent order
    variant_key = ",".join(attribut_variation)  # Create a unique key

    cart_item_defaults = {'quantity': 1}
    if attribut_variation:
        cart_item_defaults['variant_key'] = variant_key

    if request.user.is_authenticated:
        cart_item, created = CartItem.objects.get_or_create(
            product=product,
            user=request.user,
            defaults=cart_item_defaults,
        )
    else:
        cart, created = Cart.objects.get_or_create(cart_id=cart_id)
        cart_item, created = CartItem.objects.get_or_create(
            product=product,
            defaults=cart_item_defaults,
            cart=cart,
        )

    if not created:
        cart_item.quantity += 1
        cart_item.save(update_fields=['quantity'])

    if attribut_variation:
        # Assuming variants_attribut is a ManyToManyField or similar
        cart_item.variants_attribut.add(*attribut_variation)

    return redirect('cart:carts')

def diminue_item(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    if request.user.is_authenticated:
        cart_item = get_object_or_404(CartItem, user=request.user, product=product)
    else:
        cart = _card_id(request)
        cart_item = get_object_or_404(CartItem, cart__cart_id=cart, product=product)

    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
        return redirect('cart:carts')
    else:
        cart_item.delete()
        return redirect('cart:carts')

def delete_card(request, product_id):

    product = get_object_or_404(Product, id=product_id)

    if request.user.is_authenticated:
        cart_item = get_object_or_404(CartItem, user=request.user, product=product)
        # count = get_object_or_404(CartItem).objects.filter(user=request.user).count()
    else:
        cart = _card_id(request)
        cart_item = get_object_or_404(CartItem, cart__cart_id=cart, product=product)
        # count = get_object_or_404(CartItem).objects.filter(cart=cart).count()
    cart_item.delete()
    return redirect('cart:carts')


def delete_variant_card(request, product_id, key):

    product = get_object_or_404(Product, id=product_id)
    try:
        if request.user.is_authenticated:
            cart_item = CartItem.objects.get(user=request.user, product=product, variant_key=key)
            # count = CartItem.objects.all().filter(user=request.user).count()
        else:

            cart = Cart.objects.get(cart_id=_card_id(request))
            cart_item = CartItem.objects.get(cart__cart_id=cart, product=product, variant_key=key)
            count = CartItem.objects.all().filter(cart__cart_id=cart).count()
            if count == 0:
                cart.delete()
    except CartItem.DoesNotExist:
        return redirect('cart:carts')
    else:
        cart_item.delete()
        return redirect('cart:carts')


def index(request):
    total = 0
    quantity = 0
    # cart_items = []

    if request.user.is_authenticated:
        cart_items = CartItem.objects.filter(user=request.user, is_active=True).order_by('-id')
    else:
        cart, created = Cart.objects.get_or_create(cart_id=_card_id(request))
        cart_items = CartItem.objects.filter(cart__cart_id=cart, is_active=True).order_by('-id')

    for cart_item in cart_items:
        total += (cart_item.product.price * cart_item.quantity)
        quantity += cart_item.quantity

    context = {
        'total': total,
        'quantity': quantity,
        'cart_items': cart_items
    }
    return render(request, 'cart/cart.html', context)





def add_variant_card(request, product_id, key):

    product = get_object_or_404(Product, id=product_id)

    if request.user.is_authenticated:
        cart_item = get_object_or_404(CartItem, user=request.user, product=product, variant_key=key)
    else:
        cart, created = Cart.objects.get_or_create(cart_id=_card_id(request))
        cart_item = get_object_or_404(CartItem, cart__cart_id=cart, product=product, variant_key=key)
    cart_item.quantity += 1
    cart_item.save()
    return redirect('cart:carts')


def diminue_variant_item(request, product_id, key):
    product = get_object_or_404(Product, id=product_id)

    if request.user.is_authenticated:
        cart_item = get_object_or_404(CartItem, user=request.user, product=product, variant_key=key)
    else:
        cart, created = Cart.objects.get_or_create(cart_id=_card_id(request))
        cart_item = get_object_or_404(CartItem, cart__cart_id=cart, product=product, variant_key=key)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:carts')

@login_required
def checkout(request, total=0, cart_id=None, quantity=0):
    cart_items = []
    form = OrderForm()
    if request.user.is_authenticated:
        cart_items = CartItem.objects.filter(user=request.user, is_active=True).order_by('-id')
    else:
        cart = Cart.objects.get(cart_id=_card_id(request))
        cart_items = CartItem.objects.filter(cart__cart_id=cart, is_active=True).order_by('-id')
    for cart_item in cart_items:
        total += (cart_item.product.price * cart_item.quantity)
        quantity += cart_item.quantity

    context = {
        'total': total,
        'quantity': quantity,
        'cart_items': cart_items,
        'form': form
    }
    return render(request, 'cart/checkout.html', context)

store/views.py
from django.http import Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Product
from category.models import Category
from carts.models import CartItem, Cart
from carts.views import _card_id


# verifie si une categorie spécifique a été inserer dans l'url.
def index(request, category_slug=None):
    # si non récupère tous les produits disponibles si aucune categorie n'a été demanndée
    if not category_slug:
        products = Product.objects.all().filter(is_available=True)
        paginator = Paginator(products, 3)
        page_number = request.GET.get('page')
        page = paginator.get_page(page_number)
    else:
        # ici récupère tous les produits disponibles d'une categorie demanndée
        categories = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=categories, is_available=True)
        paginator = Paginator(products, 3)
        page_number = request.GET.get('page')
        page = paginator.get_page(page_number)
    count = products.count()
    context = {'products': page, 'count': count}
    return render(request, 'store/store.html', context)


def product_detail(request, category_slug, product_slug):
    single_product = get_object_or_404(Product, slug=product_slug, category__slug=category_slug)
    data = {}
    if single_product.allow_variants:
        variants = single_product.variant_products.all()
        differents_variants = set(var.variant.name for var in variants)
        for _ in differents_variants:
            var_data = []
            for variant in variants:
                if variant.variant.name == _:
                    var_data.append(variant)
            data[_] = var_data

    try:
        if request.user.is_authenticated:
            cart_item = CartItem.objects.get(product=single_product, user=request.user)
        else:
            cart_item = CartItem.objects.get(product=single_product, cart__cart_id=_card_id(request))
    except CartItem.DoesNotExist:
        cart_item = None
    cart_exist = True if cart_item else False
    context = {'single_product': single_product, 'cart_exist': cart_exist, '' if not data else 'variant': data,
               '' if not cart_exist else 'cart_item': cart_item}

    return render(request, 'store/product_detail.html', context)

def add_card(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    cart_id = _card_id(request)

    attribut_variation = [value for key, value in request.POST.items() if key != "csrfmiddlewaretoken"]
    attribut_variation.sort()  # Ensure consistent order
    variant_key = ",".join(attribut_variation)  # Create a unique key

    cart_item_defaults = {'quantity': 1}
    if attribut_variation:
        cart_item_defaults['variant_key'] = variant_key

    if request.user.is_authenticated:
        cart_item, created = CartItem.objects.get_or_create(
            product=product,
            user=request.user,
            defaults=cart_item_defaults,
        )
    else:
        cart, created = Cart.objects.get_or_create(cart_id=cart_id)
        cart_item, created = CartItem.objects.get_or_create(
            product=product,
            defaults=cart_item_defaults,
            cart=cart,
        )

    if not created:
        cart_item.quantity += 1
        cart_item.save(update_fields=['quantity'])

    if attribut_variation:
        # Assuming variants_attribut is a ManyToManyField or similar
        cart_item.variants_attribut.add(*attribut_variation)

    return redirect(product.get_url())

def diminue_item(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    if request.user.is_authenticated:
        cart_item = get_object_or_404(CartItem, user=request.user, product=product)
    else:
        cart = _card_id(request)
        cart_item = get_object_or_404(CartItem, cart__cart_id=cart, product=product)

    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
        return redirect(product.get_url())
    else:
        cart_item.delete()
        return redirect(product.get_url())

templates/store/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <section class="section-content padding-y bg p-5 h-75">
        <div class="container mt-5">

        <!-- ============================ COMPONENT 1 ================================= -->
            {% if count_item != 0 %}
                <div class="row">
                    <aside class="col-lg-9">
                <div class="card">
                <table class="table table-borderless table-shopping-cart">
                <thead class="text-muted">
                <tr class="small text-uppercase">
                  <th scope="col">Product</th>
                  <th scope="col" width="120">Quantity</th>
                  <th scope="col" width="120">Price</th>
                  <th scope="col" class="text-right" width="200"> </th>
                </tr>
                </thead>
                <tbody>
                {% for cart_item in cart_items %}
                    <tr>
                        <td>
                            <figure class="itemside align-items-center">
                                <div class="aside"><img src="{{ cart_item.product.image.url }}" class="img-sm"></div>
                                <figcaption class="info">
                                    <a href="{{ cart_item.product.get_url }}" class="title text-dark">{{ cart_item.product.product_name }}</a>
                                    {% if cart_item.product.allow_variants %}
                                        {% for attribut in cart_item.variants_attribut.all %}
                                            <p class="text-muted small">{{ attribut.variant.name }}: {{ attribut.attribut_variant_name }}</p>
                                        {% endfor %}
                                    {% endif %}
                                </figcaption>
                            </figure>
                        </td>
                        <td class="w-25">
                            <!-- col.// -->
                            <div class="col">
                                <div class="input-group input-spinner d-flex gap-1">
                                    <div class="input-group-prepend">
                                        {% if not cart_item.product.allow_variants %}
                                            <a href="{% url 'cart:diminue_item' cart_item.product.id  %}" class="btn btn-light" type="button" id="button-plus"> <i class="fa fa-minus"></i> </a>
                                        {% else %}
                                            <a href="{% url 'cart:diminue_variant_item' cart_item.product.id cart_item.variant_key %}" class="btn btn-light" type="button" id="button-plus"> <i class="fa fa-minus"></i> </a>
                                        {% endif %}
                                    </div>
                                    <input type="text" class="form-control"  value="{{ cart_item.quantity }}" disabled>
                                    <div class="input-group-append">
                                        {% if not cart_item.product.allow_variants %}
                                            <a href="{% url 'cart:add_cart' cart_item.product.id  %}" class="btn btn-light" type="button" id="button-plus"> <i class="fa fa-plus"></i> </a>
                                        {% else %}
                                            <a href="{% url 'cart:add_variant_card' cart_item.product.id cart_item.variant_key %}" class="btn btn-light" type="button" id="button-plus"> <i class="fa fa-plus"></i> </a>
                                        {% endif %}
                                    </div>
                                </div> <!-- input-group.// -->
                            </div> <!-- col.// -->
                        </td>
                        <td>
                            <div class="price-wrap">
                                <var class="price"><span class="me-2">FCFA</span><span class="fw-bolder">{{ cart_item.product.price }}</span></var>
                                <small class="text-muted"><span class="col-1">FCFA</span> <span class="">{{ cart_item.total }}</span>each </small>
                            </div> <!-- price-wrap .// -->
                        </td>
                        <td class="text-right">
                            {% if not cart_item.product.allow_variants %}
                                <a href="{% url 'cart:delete_card' cart_item.product.id  %}" class="btn btn-danger"> Remove</a>
                            {% else %}
                                <a href="{% url 'cart:delete_variant_card' cart_item.product.id cart_item.variant_key %}" class="btn btn-danger"> Remove</a>
                            {% endif %}

                        </td>
                    </tr>
                {% endfor %}
                </tbody>
                </table>
                </div> <!-- card.// -->

                    </aside> <!-- col.// -->
                    <aside class="col-lg-3">

                        <div class="card">
                        <div class="card-body">
                            <dl class="dlist-align">
                              <dt>Total price:</dt>
                              <dd class="text-right"><span class="fw-bold m1-2">FCFA</span><span>{{ total }}</span></dd>
                            </dl>
                            <dl class="dlist-align">
                              <dt>Tax:</dt>
                              <dd class="text-right"> $10.00</dd>
                            </dl>
                            <dl class="dlist-align">
                              <dt>Total:</dt>
                              <dd class="text-right text-dark b"><strong>$59.97</strong></dd>
                            </dl>
                            <hr>
                            <p class="text-center mb-3">
                                <img src="{% static 'images/misc/payments.png' %}" height="26" alt="">
                            </p>
                            <a href="{% url 'cart:checkout' %}" class="btn btn-primary btn-block"> Checkout </a>
                            <a href="{% url 'store' %}" class="btn btn-light btn-block">Continue Shopping</a>
                        </div> <!-- card-body.// -->
                        </div> <!-- card.// -->

                </aside> <!-- col.// -->


                </div> <!-- row.// -->
            {% else %}
        <!-- ============================ COMPONENT 1 END .// ================================= -->
                <div class="mx-auto w-50 text-center">
                  <h2>Votre panier est vide!</h2>
                  <p>Parcourez nos catégories et découvrez nos meilleures offres!</p>
                  <a href="{% url 'home' %}" class="btn btn-primary p-2 fa-bolder">COMMENCEZ VOS ACHATS</a>
                </div>
            {% endif %}
        </div> <!-- container .//  -->
    </section>
{% endblock %}

templates/store/product_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <div class="container mt-5">

        <!-- ============================ COMPONENT 1 ================================= -->
        <div class="card">
            <div class="row no-gutters">
                <aside class="col-md-6">
                    <article class="gallery-wrap">
                        <div class="img-big-wrap">
                           <a href="#"><img src="{{ single_product.image.url }}"></a>
                        </div> <!-- img-big-wrap.// -->
                    </article> <!-- gallery-wrap .end// -->
                </aside>
                <main class="col-md-6 border-left">
                    <article class="content-body">

                        <h2 class="title">{{ single_product.product_name }}</h2>

                        <div class="mb-3">
                            <var class="price h4"><span class="fw-lighter text-secondary">FCFA</span>&ensp;<span class="text-uppercase">{{ single_product.price }}</span></var>
                        </div>

                        <p>{{ single_product.description }}</p>

                        {% if single_product.allow_variants %}
                            <hr>
                            <div class="row">
                                {% for key, value in variant.items %}
                                    <div class="col">
                                        <label for="{{ key }}"><span class="fw-bold">{{ key }}:</span></label>
                                        <select class="form-select w-50" id="{{ key }}" name="{{ key }}" aria-label="Default select example" required>
                                            <option  selected disabled value="">Select</option>
                                            {% for attribut in value %}
                                                <option value="{{ attribut.id}}">{{ attribut.attribut_variant_name}}</option>
                                                *                    {% endfor %}
                                        </select>
                                    </div> <!-- row.// -->
                                {% endfor %}
                            </div>
                            <hr>
                        {% endif %}
                        {% if single_product.stock == 0 %}
                            <span class="text-danger fs-3"> Hors Stock</span>
                        {% else %}
                            {% if cart_exist %}
                                <div class="row">
                                    <a href="#" class="btn  btn-success"> <span class="text">Added to cart</span> <i class="fas fa-check"></i>  </a>
{#                                        <a href="{% url 'cart:carts' %}" class="btn  btn-outline-primary col"> <span class="text">View Cart</span> <i class="fas fa-eye"></i>  </a>#}
                                    <!-- col.// -->
                                    <div class="col">
                                        <div class="input-group input-spinner">
                                            <div class="input-group-prepend">
                                                <form action="{% url 'diminue_item' cart_item.product.id %}">
                                                    {% csrf_token %}
                                                    <button class="btn btn-light" type="submit" id="button-minus"> <i class="fa fa-minus"></i> </button>
                                                </form>                                                </div>
                                            <input type="text" class="form-control"  value="{{ cart_item.quantity }}">
                                            <div class="input-group-append">
                                                 <form action="{% url 'add_cart' cart_item.product.id %}">
                                                    {% csrf_token %}
                                                    <button class="btn btn-light" type="submit" id="button-minus"> <i class="fa fa-plus"></i> </button>
                                                </form>
                                            </div>
                                        </div> <!-- input-group.// -->
                                    </div> <!-- col.// -->
                                </div>
                            {% else %}
                                {% if single_product.allow_variants %}
                                    <form action="{% url 'cart:add_cart' single_product.id%}" method="post">
                                {% else %}
                                    <form action="{% url 'cart:add_cart' single_product.id%}" method="post">
                                {% endif %}
                                    {% csrf_token %}
                                    <button class="btn  btn-primary"> <span class="text">Add to cart</span> <i class="fas fa-shopping-cart"></i>  </button>
                                </form>
                            {% endif %}
                        {% endif %}
                    </article> <!-- product-info-aside .// -->
                </main> <!-- col.// -->
                </div> <!-- row.// -->
            </div> <!-- card.// -->
            <!-- ============================ COMPONENT 1 END .// ================================= -->

            <br>

            <div class="row">
                        <div class="col-md-9">

                <header class="section-heading">
                    <h3>Customer Reviews </h3>

                </header>

                <article class="box mb-3">
                    <div class="icontext w-100">
                        <img src="{% static 'images/avatars/avatar1.jpg' %}" class="img-xs icon rounded-circle">
                        <div class="text">
                            <h6 class="mb-1">Mike John </h6>
                            <span class="date text-muted float-md-right">24.04.2020 </span>
                        </div>
                    </div> <!-- icontext.// -->
                    <div class="mt-3">
                        <p>
                            Dummy comment Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                            tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                            quis nostrud exercitation ullamco laboris nisi ut aliquip
                        </p>
                    </div>
            </article>



            </div> <!-- col.// -->
        </div> <!-- row.// -->


    </div>
{% endblock %}